export const AUTH_CLIENT_PROTOCOL = "wc";
export const AUTH_CLIENT_VERSION = 1;
export const AUTH_CLIENT_CONTEXT = "auth";

export const AUTH_CLIENT_STORAGE_PREFIX = `${AUTH_CLIENT_PROTOCOL}@${AUTH_CLIENT_VERSION}:${AUTH_CLIENT_CONTEXT}:`;
